export { default as About } from './About/About'
export { default as Banner } from './Banner/Banner'
export { default as Stevent } from './Stevent/Stevent'
export { default as FishTime } from './FishTime/FishTime'
export { default as Automatarium } from './Automatarium/Automatarium'
export { default as Gallery } from './Gallery/Gallery'
export { default as Cave } from './Cave/Cave'
export { default as Footer } from './Footer/Footer'
