export { default as About } from './About/About'
export { default as Banner } from './Banner/Banner'
export { default as Stevent } from './Stevent/Stevent'
export { default as FishTime } from './FishTime/FishTime'
export { default as Automatarium } from './Automatarium/Automatarium'
